### ISSUE TITLE
mariadbが立ち上がらなかったので

### ISSUE THREAD

**Issue by t-sgmt** [KeisukeKudo/laravel-container#1]
https://github.com/KeisukeKudo/laravel-container/blob/70351ce91927d6e5f580d48c9d3825ebd0d4018c/docker-compose.yml#L38-L40

mariadbが立ち上がらなかったので
mysql→mariadbに変えたら動いた

```
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mariadb
```

**Comment by KeisukeKudo** [comment]
@t-sgmt 
環境の問題かも?
Docker Desktop (Win: 2.0.0.3, Mac: 2.0.4.1)で正常に起動します｡
close #1
